name: Setup asdf - chilliisnice
description: Install tools versioned with asdf
author: Saphira <chilliisnice@wallwisher.com>
runs:
  using: node16
  main: main.js
inputs:
  asdf_branch:
    description: asdf branch to clone
    required: false
    default: master
